openapi: 3.0.3
info:
  title: Task API
  version: 1.0.0
paths:
  /tasks:
    get:
      summary: Get all tasks
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTask'
      responses:
        '201':
          description: Task created
    put:
      summary: Update a task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTask'
      responses:
        '200':
          description: Task updated
components:
  schemas:
    Task:
      type: object
      required: [id, title, checked]
      properties:
        id:
          type: string
        title:
          type: string
        checked:
          type: boolean
        lastChecked:
          type: string
          format: date-time
        frequency:
          type: string
          enum: [daily, weekly]
    NewTask:
      type: object
      required: [title]
      properties:
        title:
          type: string
        frequency:
          type: string
          enum: [daily, weekly]
    UpdateTask:
      type: object
      required: [id, checked]
      properties:
        id:
          type: string
        checked:
          type: boolean
        lastChecked:
          type: string
          format: date-time
